### ISSUE TITLE
"failed to read cargo metadata" on nightly Rust

### ISSUE THREAD

**Issue by Kogia-sima** [dtolnay/trybuild#77]
`trybuild` test cases always fail with the following error on nightly compiler.

```console
ERROR: failed to read cargo metadata: EOF while parsing a value at line 1 column 0
```

However, it still pass on stable compiler.

I've confirmed that the same test cases was working at Jun 11, 2020, 10:49 AM UTC. Maybe it is caused by changing of the manifest format in Rust?

[Link to build log](https://travis-ci.org/github/Kogia-sima/sailfish/jobs/697506455)

<details>
<summary>Full output:</summary>

```console
test compile_error ... FAILED

failures:

---- compile_error stdout ----
thread 'compile_error' panicked at 'tests failed', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.28/src/run.rs:38:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::begin_panic
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libstd/panicking.rs:404
  13: trybuild::run::<impl trybuild::Runner>::run::{{closure}}
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.28/src/run.rs:38
  14: core::result::Result<T,E>::unwrap_or_else
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libcore/result.rs:853
  15: trybuild::run::<impl trybuild::Runner>::run
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.28/src/run.rs:36
  16: <trybuild::TestCases as core::ops::drop::Drop>::drop
             at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.28/src/lib.rs:274
  17: core::ptr::drop_in_place
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libcore/ptr/mod.rs:184
  18: compile::compile_error
             at integration-tests/tests/compile.rs:26
  19: compile::compile_error::{{closure}}
             at integration-tests/tests/compile.rs:22
  20: core::ops::function::FnOnce::call_once
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libcore/ops/function.rs:232
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/liballoc/boxed.rs:1076
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libstd/panic.rs:318
  23: std::panicking::try::do_call
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libstd/panicking.rs:297
  24: std::panicking::try
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libstd/panicking.rs:274
  25: std::panic::catch_unwind
             at /rustc/a37c32e2d5fb186627ffe99a391c7fd6fd159334/src/libstd/panic.rs:394
  26: test::run_test_in_process
             at src/libtest/lib.rs:541
  27: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by dtolnay** [comment]
Nightly Cargo is super broken right now (https://github.com/rust-lang/cargo/issues/8351). I am closing because if this started happening today then it's almost certainly that. Please let me know if the next nightly release still fails the same way.
